export const types = {
    GROUP_DATA : "GROUP_DATA",
    GROUP_DATA_FAIL : "GROUP_DATA",
    GROUP_LOCKS_DATA : "GROUP_LOCKS_DATA",
    GROUP_LOCKS_DATA_FAIL : "GROUP_LOCKS_DATA_FAIL",
    GROUP_LOCKS_DATA_DELETE : "GROUP_LOCKS_DATA_DELETE",
    GROUP_LOCKS_DATA_DELETE_FAIL : "GROUP_LOCKS_DATA_DELETE_FAIL",
    GROUP_PLACES  : "GROUP_PLACES",
    GROUP_LOCKS : "GROUP_LOCKS"
}
